spring:
  application:
    name: feynman-learning-studio-backend
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:feynman_learning_studio;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    druid:
      validation-query: SELECT 1
  sql:
    init:
      mode: always

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    path: /v3/api-docs

server:
  port: 8080
