create table if not exists learning_topic (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    slug varchar(80) not null,
    description varchar(1000),
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_learning_topic_slug unique (slug),
    constraint ck_learning_topic_slug_format check (slug regexp '^[a-z0-9]+(-[a-z0-9]+)*$')
);

create table if not exists learning_experiment (
    id bigint generated by default as identity primary key,
    topic_id bigint not null,
    title varchar(160) not null,
    summary varchar(1000),
    difficulty varchar(32) not null,
    status varchar(32) not null,
    spec_path varchar(500),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_learning_experiment_topic foreign key (topic_id) references learning_topic (id),
    constraint ck_learning_experiment_difficulty check (difficulty in ('BEGINNER', 'INTERMEDIATE', 'ADVANCED')),
    constraint ck_learning_experiment_status check (status in ('DRAFT', 'READY', 'RUNNING', 'COMPLETED', 'ARCHIVED'))
);

create index if not exists idx_learning_experiment_topic_id on learning_experiment (topic_id);
create index if not exists idx_learning_topic_created_at_id on learning_topic (created_at, id);
create index if not exists idx_learning_experiment_created_at_id on learning_experiment (created_at, id);
